%** V0000 *****************************************************************************************;
%** Program   : stp_session.sas                                                                  **;
%** On LAN    : No                                                                               **;
%** On Server : Yes                                                                              **;
%** Date      : 13NOV2009                                                                        **;
%** Author    : Michael Dixon                                                                    **;
%** Owner     : BCA                                                                              **;
%** Purpose   : Wrap the STP session functions so that code using them can be used outside       **;
%**             the STP Server                                                                   **;
%**                                                                                              **;
%** Notes     : Examples: stp_session(create)      <-- Create a session                          **;
%**                       stp_session(create,600)  <-- Create a session with 10min timeout       **;
%**                       stp_session(delete)      <-- Delete a session                          **;
%**                                                                                              **;
%** ---------------------------------------------------------------------------------------------**;
%** History                                                                                      **;
%**                                                                                              **;
%** Version   :                                                                                  **;
%** Date      :                                                                                  **;
%** Author    :                                                                                  **;
%** Reason    :                                                                                  **;
%**                                                                                              **;
%**                                                                                              **;
%**************************************************************************************************;
%macro stp_session(action,parm1,parm2);
  %let ACTION = %upcase(&ACTION);
  %if %str(&ACTION) = %str( ) %then %let ACTION = CREATE;

  %if (%str(&SYSPROCESSNAME) = %str(Object Server) OR %str(&SYSPROCESSNAME) = %str(OBJECT_EXECUTIVE)) AND &SYSUSERID = sassrv %then %do; 
    %* We are running in the STP Server;
    %if &ACTION = CREATE %then %do;
      %if NOT %symexist(_SESSIONID) %then %do;
        %if %str(&PARM1) NE %str( ) %then %let PARM1=%str(,&PARM1);
        %let rc=%sysfunc(stpsrv_session(create &PARM1));
        %put NOTE: STP Session created: &_SESSIONID;
      %end;
      %else %do;
        %put NOTE: STP Session is &_SESSIONID;
      %end;
    %end;
    %else %if &ACTION = DELETE %then %do;
      %if NOT %symexist(_SESSIONID) %then %do;
        %put NOTE: No Session exists - no action taken.;
        %return;
      %end;
      %else %do;
        %let rc=%sysfunc(stpsrv_session(delete));
      %end;
    %end;
  %end;
  %else %do;
    %put NOTE: Not running in STP Server - No action taken.;
  %end;
%mend;
